AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
Description: payment order application

Parameters:
  Project:
    Type: String
    Default: pavikon-payment-order
    Description: project name
  Domain:
    Type: String
    Default: com-pavelshapel
    Description: domain name

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Domain}-${Project}-source-bucket'

  TargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Domain}-${Project}-target-bucket'

  PaymentOrderSqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${Project}-sqs'

  NbrbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: nbrb
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  FilePlaceholderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-file-placeholder-function'
      CodeUri: .\aws-lambda-service-file-placeholder\target\aws-lambda-service-file-placeholder-1.0.0-shaded.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          FUNCTION_NAME: filePlaceholderRequestHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 15
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaSQSQueueExecutionRole
        - AmazonS3FullAccess
      Events:
        PaymentOrderSqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PaymentOrderSqs.Arn
            BatchSize: 10
  NbrbFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-nbrb-function'
      CodeUri: .\aws-lambda-service-nbrb\target\aws-lambda-service-nbrb-1.0.0-shaded.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          FUNCTION_NAME: nbrbRequestHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 15
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess