package com.pavelshapel.aws.lambda.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import static com.pavelshapel.aws.lambda.entity.Product.TABLE_NAME;

@DynamoDBTable(tableName = TABLE_NAME)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product {
    public static final String TABLE_NAME = "product";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String price;

    public Product(String name, String price) {
        this.name = name;
        this.price = price;
    }
}