package com.pavelshapel.aws.lambda.service.nbrb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.pavelshapel.core.spring.boot.starter.api.model.Entity;
import com.pavelshapel.core.spring.boot.starter.api.model.Named;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldDefaults;

import java.util.Date;

import static com.pavelshapel.aws.lambda.service.nbrb.model.Nbrb.TABLE_NAME;
import static com.pavelshapel.common.module.dto.aws.NbrbDto.DATE_PATTERN;

@Data
@NoArgsConstructor
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
@DynamoDBTable(tableName = TABLE_NAME)
public class Nbrb implements Entity<String>, Named {
    public static final String TABLE_NAME = "nbrb";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String id;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedTimestamp(pattern = DATE_PATTERN)
    Date date;

    @DynamoDBAttribute
    String abbreviation;

    @DynamoDBAttribute
    Integer scale;

    @DynamoDBAttribute
    String name;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    Double rate;

    @Override
    public int compareTo(Entity<String> entity) {
        return getId().compareTo(entity.getId());
    }
}
