server:
  port: 80
spring:
  aop:
    proxy-target-class: false
  application:
    name: @project.artifactId@:@project.version@
    description: @project.description@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tutorial-db-instance.ctacsjbk6g8a.eu-west-1.rds.amazonaws.com:5432/sample
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
