server:
  port: 9001
spring:
  aop:
    proxy-target-class: false
  application:
    name: @project.artifactId@:@project.version@
    description: @project.description@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kafka_client
    username: postgres
    password: postgres
    initialization-mode: never
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/kafka_client
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yml