package com.pavelshapel.aws.lambda.service.location.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.pavelshapel.aws.lambda.service.location.model.converter.LocationParentalDynamoDBTypeConverter;
import com.pavelshapel.core.spring.boot.starter.api.model.ParentalEntity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import static com.pavelshapel.aws.lambda.service.location.model.Location.TABLE_NAME;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = TABLE_NAME)
public class Location implements ParentalEntity<String, Location> {
    public static final String TABLE_NAME = "location";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBTypeConverted(converter = LocationParentalDynamoDBTypeConverter.class)
    @DynamoDBAttribute
    private Location parent;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private LocationType locationType;
}

