spring:
  aws:
    dynamodb:
      enabled: true
      object: nbrb
    s3:
      enabled: true
      object: com-pavelshapel-backup-bucket
  webflux:
    web-client:
      enabled: true
      base-url: https://www.nbrb.by/api
      timeout: 1000