version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to disable scribe
      # - SCRIBE_ENABLED=false
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
    ports:
      - 9411:9411
  graphite:
    container_name: graphite
    image: graphiteapp/graphite-statsd
    ports:
      - 2003:2003
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - 8500:8500
  cloud-provider:
    container_name: cloud-provider
    image: pavelshapel/cloud-provider:1.00
    ports:
      - 9001:9001
    depends_on:
      - consul
      - zipkin
      - graphite
  cloud-consumer:
    container_name: cloud-consumer
    image: pavelshapel/cloud-consumer:1.00
    ports:
      - 9002:9002
    depends_on:
      - consul
      - zipkin
      - graphite
  cloud-gateway:
    container_name: cloud-gateway
    image: pavelshapel/cloud-gateway:1.00
    ports:
      - 9003:9003
    depends_on:
      - consul
      - zipkin
      - graphite
      - cloud-consumer
      - cloud-provider

